services:
    kasimi.movetopicswhenlocked.listener:
        class: kasimi\movetopicswhenlocked\event\listener
        arguments:
            - '@user'
            - '@auth'
            - '@request'
            - '@dbal.conn'
            - '@template'
            - '@log'
            - '@config'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
